---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: check kubectl installed
      ansible.builtin.command: "kubectl version --client"
      changed_when: no

    - name: check helm installed
      ansible.builtin.command: "helm version"
      changed_when: no
